{
 "title": "vCE",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "vim_uuid", "label": "VIM", "query": "Opennebula" },
   {
    "name": "VNF",
    "label": "VNF",
    "query": "SELECT \"vdu_name\" FROM /vce_vnf_measurements/ WHERE vdu_mac =~/$vdu_mac/"
   },
   {
    "name": "vdu_mac",
    "label": "VDU",
    "query": "SHOW TAG VALUES FROM /vce_vnf_measurements/ WITH KEY = \"vdu_mac\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Actual bitrate",
   "type": "gauge",
   "description": "Actual bitrate",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "act_bitrate" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Quality Profile",
   "type": "singlestat",
   "description": "Quality Profile",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "vce_vnf_measurements",
     "query": "SELECT \"value\" FROM \"vce_vnf_measurements\" WHERE (\"metric\" = 'num_fps' AND \"vdu_mac\" =~ /^$vdu_mac$/) AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "metric_z" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "SS-CNO capped min bitrate",
   "type": "gauge",
   "description": "SS-CNO capped min bitrate",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "metric_x" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "SS-CNO capped max bitrate",
   "type": "gauge",
   "description": "SS-CNO capped max bitrate",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "measurement": "vce_vnf_measurements",
     "query": "SELECT \"value\" FROM \"vce_vnf_measurements\" WHERE (\"metric\" = 'metric_y' AND \"vdu_mac\" =~ /^$vdu_mac$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "metric_y" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Encoding quality",
   "type": "gauge",
   "description": "Encoding quality",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "measurement": "vce_vnf_measurements",
     "query": "SELECT 69 - \"value\" FROM \"vce_measurements\" WHERE (\"metric\" = 'enc_quality') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "enc_quality" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Encoding quality",
   "type": "gauge",
   "description": "Avg. Encoding quality",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "measurement": "vce_vnf_measurements",
     "query": "SELECT 69 - \"value\" FROM \"vce_measurements\" WHERE (\"metric\" = 'enc_quality') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "enc_quality" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Current fps",
   "type": "gauge",
   "description": "Current fps",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "measurement": "vce_vnf_measurements",
     "query": "SELECT \"value\" FROM \"vce_vnf_measurements\" WHERE (\"metric\" = 'num_fps' AND \"vdu_mac\" =~ /^$vdu_mac$/) AND $timeFilter limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "num_fps" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Group of pictures size",
   "type": "singlestat",
   "description": "Group of pictures size",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "gop_size",
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "gop_size" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Actual bitrate",
   "type": "graph",
   "description": "Actual bitrate",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "actual_bitrate",
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "act_bitrate" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Target bitrate",
   "type": "graph",
   "description": "Max bitrate",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "target_bitrate",
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "max_bitrate" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "SS-CNO capped min/max bitrate",
   "type": "graph",
   "description": "SS-CNO capped min/max bitrate",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "max bitrate",
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "metric_y" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    },
    {
     "alias": "min bitrate",
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "metric_x" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Encoded quality",
   "type": "graph",
   "description": "Encoded quality",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "enc_quality",
     "measurement": "vce_vnf_measurements",
     "query": "SELECT 69- \"value\" FROM \"vce_measurements\" WHERE (\"metric\" = 'enc_quality') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "enc_quality" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Encoding speed",
   "type": "graph",
   "description": "Encoding speed",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "enc_speed",
     "measurement": "vce_vnf_measurements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "enc_speed" },
      { "condition": "AND", "key": "vdu_mac", "operator": "=~", "value": "/^$vdu_mac$/" }
     ]
    }
   ]
  }
 ]
}